# Generated by Django 4.1.6 on 2023-02-13 15:08

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', froala_editor.fields.FroalaField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
