# Generated by Django 4.1.6 on 2023-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='integrate-froala-with-django', unique=True),
            preserve_default=False,
        ),
    ]
