# Generated by Django 4.1.6 on 2023-03-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('avatar', models.ImageField(upload_to='blog/authors/')),
                ('github', models.URLField(default='https://github.com/', max_length=300)),
                ('instagram', models.URLField(default='https://instagram.com/', max_length=300)),
                ('twitter', models.URLField(default='https://twitter.com/', max_length=300)),
                ('email', models.EmailField(default='thisemail@doesnotexists.com', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.postauthor'),
        ),
    ]
