# Generated by Django 4.1.6 on 2023-03-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postauthor_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
