# Generated by Django 4.1.7 on 2023-04-16 16:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpost_likes_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='https://google.com/image/cool.png', upload_to=blog.models.BlogPost.get_upload_path),
            preserve_default=False,
        ),
    ]
