# Generated by Django 4.1.6 on 2023-02-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/<django.db.models.fields.SlugField>/images/')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('project_link', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/<property object at 0x0000027AE03FB5B0>/images/')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolioitem')),
            ],
        ),
    ]
