# Generated by Django 4.1.6 on 2023-02-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/<property object at 0x000001C6C7B3F650>/images/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
