# Generated by Django 4.1.6 on 2023-02-12 18:18

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='thumbnail',
            field=models.ImageField(upload_to=portfolio.models.PortfolioItem.get_upload_path),
        ),
    ]
