# Generated by Django 4.1.1 on 2022-09-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=300)),
            ],
        ),
    ]
