# Generated by Django 4.1.1 on 2022-09-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysociallink',
            old_name='classes',
            new_name='fa_classes',
        ),
        migrations.RenameField(
            model_name='mysociallink',
            old_name='link',
            new_name='url',
        ),
    ]
