# Generated by Django 4.1.1 on 2022-09-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehome', '0003_timelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='date',
            field=models.DateField(),
        ),
    ]
